-- ============================================================================
-- View leve de Manifestos para o Dashboard
-- ============================================================================

CREATE OR ALTER VIEW dbo.vw_fato_manifestos_dash AS
SELECT
    hora_solicitacao                 AS [Hora (Solicitacao)],
    hora_criacao                     AS [Hora (Criação)],
    sequence_code                    AS [Número],
    identificador_unico              AS [Identificador Único],
    status                           AS [Status],
    classificacao                    AS [Classificação],
    filial                           AS [Filial],
    filial_emissora                  AS [Filial Emissora],
    data_criacao                     AS [Data criação],
    saida                            AS [Saída],
    fechamento                       AS [Fechamento],
    chegada                          AS [Chegada],
    mdfe_number                      AS [MDFe],
    mdfe_key                         AS [MDF-es/Chave],
    mdfe_status                      AS [MDFe/Status],
    distribution_pole                AS [Polo de distribuição],
    placa_veiculo                    AS [Veículo/Placa],
    tipo_veiculo                     AS [Tipo Veículo],
    proprietario_nome                AS [Proprietário/Nome],
    proprietario_documento           AS [Proprietário/Documento],
    tipo_motorista                   AS [Tipo Motorista],
    motorista                        AS [Motorista],
    km_saida                         AS [Km saída],
    km_chegada                       AS [Km chegada],
    km_viagem                        AS [KM viagem],
    km_manual                        AS [Km manual],
    qtd_nf                           AS [Qtd NF],
    volumes_nf                       AS [Volumes NF],
    peso_nf                          AS [Peso NF],
    peso_taxado                      AS [Total peso taxado],
    total_m3                         AS [Total M3],
    valor_nf                         AS [Valor NF],
    fretes_total                     AS [Fretes/Total],
    coletas_total                    AS [Coletas/Total],
    receita_total                    AS [Receita Total Transportada],
    coleta_numeros                   AS [Coleta/Número],
    contract_number                  AS [CIOT/Número],
    tipo_contrato                    AS [Tipo de contrato],
    tipo_calculo                     AS [Tipo de cálculo],
    tipo_carga                       AS [Tipo de carga],
    diaria                           AS [Diária],
    custo_total                      AS [Custo total],
    valor_frete                      AS [Valor frete],
    combustivel                      AS [Combustível],
    pedagio                          AS [Pedágio],
    servicos_motorista_total         AS [Serviços motorista/Total],
    despesa_operacional              AS [Despesa operacional],
    inss_value                       AS [Dados do agregado/INSS],
    sest_senat_value                 AS [Dados do agregado/SEST/SENAT],
    ir_value                         AS [Dados do agregado/IR],
    saldo_pagar                      AS [Saldo a pagar],
    uniq_destinations_count          AS [Destinos únicos/Qtd],
    gerar_mdfe                       AS [Gerar MDF-e],
    solicitou_monitoramento          AS [Solicitou Monitoramento],
    solicitacao_monitoramento        AS [Solicitação Monitoramento],
    leitura_movel_em                 AS [Leitura Móvel/Em],
    km_total                         AS [KM Total],
    itens_entrega                    AS [Itens/Entrega],
    itens_transferencia              AS [Itens/Transferência],
    itens_coleta                     AS [Itens/Coleta],
    itens_despacho_rascunho          AS [Itens/Despacho Rascunho],
    itens_consolidacao               AS [Itens/Consolidação],
    itens_coleta_reversa             AS [Itens/Coleta Reversa],
    itens_total                      AS [Itens/Total],
    itens_finalizados                AS [Itens/Finalizados],
    calculado_coleta                 AS [Calculado/Coleta],
    calculado_entrega                AS [Calculado/Entrega],
    calculado_despacho               AS [Calculado/Despacho],
    calculado_consolidacao           AS [Calculado/Consolidação],
    calculado_coleta_reversa         AS [Calculado/Coleta Reversa],
    valor_coletas                    AS [Valor/Coletas],
    valor_entregas                   AS [Valor/Entregas],
    despachos                        AS [Despachos],
    consolidacoes                    AS [Consolidações],
    coleta_reversa                   AS [Coleta Reversa],
    adiantamento                     AS [Adiantamento],
    custos_frota                     AS [Custos Frota],
    adicionais                       AS [Adicionais],
    descontos                        AS [Descontos],
    desconto_valor                   AS [Desconto/Valor],
    ajuste_comentarios               AS [Liberação de Custo de Agregado/Comentários],
    iks_id                           AS [IKS ID],
    programacao_sequence_code        AS [Programação/Número],
    programacao_inicio               AS [Programação/Início],
    programacao_termino              AS [Programação/Término],
    carreta1_placa                   AS [Carreta 1/Placa],
    carreta1_capacidade_peso         AS [Carreta 1/Capacidade Peso],
    carreta2_placa                   AS [Carreta 2/Placa],
    carreta2_capacidade_peso         AS [Carreta 2/Capacidade Peso],
    veiculo_capacidade_peso          AS [Veículo/Capacidade Peso],
    veiculo_peso_cubado              AS [Veículo/Peso Cubado],
    capacidade_lotacao_kg            AS [Capacidade Lotação Kg],
    descarregamento_destinatarios    AS [Descarregamento/Destinatários],
    local_descarregamento            AS [Local de Descarregamento],
    entrega_regioes                  AS [Entrega/Regiões],
    programacao_cliente              AS [Programação/Cliente],
    programacao_tipo_servico         AS [Programação/Tipo Serviço],
    usuario_emissor                  AS [Usuário/Emissor],
    usuario_ajuste                   AS [Usuário/Ajuste],
    obs_operacional                  AS [Liberação/Comentários Operacionais],
    obs_financeira                   AS [Comentários Fechamento],
    metadata                         AS [Metadata],
    data_extracao                    AS [Data de extracao]
FROM dbo.fato_gestao_vista_manifestos
WHERE excluido_na_origem = 0;
GO

PRINT 'View dbo.vw_fato_manifestos_dash criada/atualizada com sucesso.';
GO
